# Generated by Django 3.0 on 2022-02-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.FileField(upload_to='staticfiles/files/'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='thumbnail',
            field=models.ImageField(upload_to='staticfiles/img/'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/img/'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/img/'),
        ),
    ]
