# Generated by Django 3.0 on 2022-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220219_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/img/'),
        ),
    ]
