# Generated by Django 4.0.2 on 2022-02-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_papers_subjects_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='subject',
            field=models.CharField(default='Maths', max_length=50),
            preserve_default=False,
        ),
    ]
