# Generated by Django 3.0 on 2022-02-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220219_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/img/'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/img/'),
        ),
    ]
