# Generated by Django 3.0 on 2022-02-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220222_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/img/'),
        ),
    ]
