# Generated by Django 3.0 on 2022-02-12 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220211_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.Subjects'),
        ),
    ]
