# Generated by Django 3.0 on 2022-02-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220212_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='papers',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papers',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='api.Subjects'),
        ),
    ]
